export default interface IInvoicePaymentExternal {
  id: string,
  dueDate: string,
  amount: number,
  finalAmount: number,
  fineAmount: number,
  interestAmount: number,
  discountAmount: number,
  finePercentage: number,
  interestPercentage: number,
  pixCode: string,
  pixQrCodeBase64: string | null,
  picPayCode: string | null,
  picPayQrCodeBase64: string | null,
  billetDigitableLine: string,
  billetBarcodeBase64: string | null,
  canSetRecurrence: boolean,
  canPayInvoiceByCreditCard: boolean,
  maximumCreditCardInstallments: number,
  customerName: string | null,
  billetOurNumber: string,
  invoicePDFURL: string,
  negotiationLink: string | null
}